begin;
create extension if not exists pgtap with schema extensions;
\ir helpers/_betting_fixtures.sql.inc
\ir helpers/_season_end_report.sql.inc
select plan(15);

select test_profile(6100) as staff \gset

select ok(not has_function_privilege('anon', 'public.begin_season_end_opening(uuid,text,uuid,text)', 'execute'), 'anonymous callers cannot execute the recreated opening RPC');
select ok(not has_function_privilege('authenticated', 'public.begin_season_end_opening(uuid,text,uuid,text)', 'execute'), 'authenticated callers cannot execute the recreated opening RPC');
select ok(has_function_privilege('service_role', 'public.begin_season_end_opening(uuid,text,uuid,text)', 'execute'), 'service role retains opening RPC access');
select ok(not has_function_privilege('anon', 'public.approve_season_end_release(uuid,text,text)', 'execute'), 'anonymous callers cannot approve releases');
select ok(not has_function_privilege('authenticated', 'public.approve_season_end_release(uuid,text,text)', 'execute'), 'authenticated callers cannot approve releases');
select has_function('public', 'lock_season_end_related_offers', array['bigint[]', 'bigint', 'bigint'], 'trade settlement exposes a complete-set related-offer lock boundary');
select is(public.season_end_canonical_json('{"x":1.0,"y":2.50,"nested":[0.25,100000]}'::jsonb), '{"nested":[0.25,100000],"x":1,"y":2.5}', 'report canonicalization normalizes JSON numbers like the simulator');
select is(public.season_end_canonical_json('{"small":0.00000009999999999,"large":1000000000000000000000}'::jsonb), '{"large":1000000000000000000000,"small":0.00000009999999999}', 'report canonicalization matches JavaScript decimal serialization for exponent-range values');

-- The digest below was generated by the production JavaScript serializer and
-- deliberately bypasses the SQL helper's digest. The successful import below
-- therefore proves a JavaScript-generated report crosses the database boundary.
create or replace function test_javascript_season_end_report(p_release uuid)
returns jsonb
language sql
as $$
  select jsonb_build_object(
    'reportDigest', 'e3de2222d2d08dc322037ccc3e7c2a400a6ca359485453925174198aa2823b66',
    'evidence', test_season_end_report(p_release) -> 'evidence'
  );
$$;

insert into public.season_end_releases
  (id, league, season, state, price, catalog_hash, rules_version, revision_digest, signature_calibration, created_by)
values
  ('00000000-0000-0000-0000-000000001927', 'premier', 'S_TEST_0127', 'admin_test', 500, 'hash-0127', 'rules-0127', 'revision-0127', '{"calibratedPerCopyChance":0.01,"achievablePackProbability":0.01}', :'staff');

select throws_ok(format($sql$ select public.record_season_end_verification_report(
  '00000000-0000-0000-0000-000000001927'::uuid,
  'revision-0127',
  test_javascript_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) ->> 'reportDigest',
  test_javascript_season_end_report('00000000-0000-0000-0000-000000001927'::uuid),
  %L
) $sql$, :'staff'), 'P0001', null, 'a report cannot pass without an exact fulfilled opening');

select throws_ok($$ select public.record_season_end_verification_report(
  '00000000-0000-0000-0000-000000001927'::uuid,
  'revision-0127',
  repeat('0', 64),
  test_rewrap_season_end_report(
    test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid),
    jsonb_set(
      jsonb_set(test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) -> 'evidence', '{scenarios,standard}', 'null'::jsonb),
      '{scenarios,maximumPatron}', 'null'::jsonb
    )
  ),
  'release-staff'
) $$, 'P0001', null, 'a report with missing scenarios cannot be recorded');

insert into public.season_end_openings
  (opening_id, request_id, discord_id, release_id, mode, status, price, revision_digest, economy_version, economy_payload, rules_version, rules_payload)
values
  ('00000000-0000-0000-0000-000000002701', '00000000-0000-0000-0000-000000002711', :'staff', '00000000-0000-0000-0000-000000001927', 'admin_test', 'fulfilled', 500, 'revision-0127', 'season-end-economy-2026-09-v1', '{}', 'rules-0127', '{}');

select throws_ok(format($sql$ select public.record_season_end_verification_report(
  '00000000-0000-0000-0000-000000001927'::uuid,
  'revision-0127',
  (test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) ->> 'reportDigest'),
  test_rewrap_season_end_report(test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid), jsonb_set(test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) -> 'evidence', '{acceptance,maximumPatronSalvageUpperBound}', '-1'::jsonb)),
  %L
) $sql$, :'staff'), 'P0001', null, 'a negative maximum-patron bound cannot be recorded');

select throws_ok(format($sql$ select public.record_season_end_verification_report(
  '00000000-0000-0000-0000-000000001927'::uuid,
  'revision-0127',
  (test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) ->> 'reportDigest'),
  test_rewrap_season_end_report(test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid), jsonb_set(test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) -> 'evidence', '{inputDigest}', to_jsonb(repeat('f', 64)))),
  %L
) $sql$, :'staff'), 'P0001', null, 'a wrong frozen-input hash cannot be recorded');

select lives_ok(format($sql$ select public.record_season_end_verification_report(
  '00000000-0000-0000-0000-000000001927'::uuid,
  'revision-0127',
  test_javascript_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) ->> 'reportDigest',
  test_javascript_season_end_report('00000000-0000-0000-0000-000000001927'::uuid),
  %L
) $sql$, :'staff'), 'a complete report with one exact fulfilled opening is recordable');
select is((select count(*)::int from public.season_end_release_reports where release_id = '00000000-0000-0000-0000-000000001927'::uuid), 1, 'the accepted report is stored once');

select throws_ok(format($sql$ select public.record_season_end_verification_report(
  '00000000-0000-0000-0000-000000001927'::uuid,
  'revision-0127',
  test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) ->> 'reportDigest',
  test_rewrap_season_end_report(test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid), jsonb_set(test_season_end_report('00000000-0000-0000-0000-000000001927'::uuid) -> 'evidence', '{acceptance,exactRevisionOpeningCount}', '2'::jsonb)),
  %L
) $sql$, :'staff'), 'P0001', null, 'a report cannot be replaced under an existing digest');

select * from finish();
rollback;
