export interface FreeAgencyPlayer { name: string; avgBid: number | null; }
export interface FreeAgencyCaptain { name: string; players: FreeAgencyPlayer[]; }

// Imported from the public Google Sheet CSV export; all Avg Bid values are integers.
export const FREE_AGENCY_PLAYER_SUMMARIES: FreeAgencyPlayer[] = [
  { name: "Canny#rip", avgBid: 46 },
  { name: "Matrix#NA101", avgBid: 40 },
  { name: "Pinei nessa poha#00027", avgBid: 40 },
  { name: "LotusB5#999", avgBid: 39 },
  { name: "JayDK#NA1", avgBid: 38 },
  { name: "Killer Python#NA1", avgBid: 38 },
  { name: "Doug#LIMU", avgBid: 37 },
  { name: "VIP Peekaboo#VIP", avgBid: 37 },
  { name: "Chief#1160", avgBid: 36 },
  { name: "Aura#5950", avgBid: 33 },
  { name: "Walt#0001", avgBid: 33 },
  { name: "Qball#1032", avgBid: 32 },
  { name: "Zoodiac#すべて同じ", avgBid: 32 },
  { name: "Superbeans#222", avgBid: 31 },
  { name: "Dariss#na1", avgBid: 30 },
  { name: "Rutledge#osu", avgBid: 28 },
  { name: "Cherrie", avgBid: 27 },
  { name: "MMO#NA1", avgBid: 27 },
  { name: "GratxAce#NA1", avgBid: 25 },
  { name: "i fear nobody#na1", avgBid: 25 },
  { name: "Thunder Master#BLOOD", avgBid: 25 },
  { name: "YWGI#rain", avgBid: 24 },
  { name: "Crabadabadoo", avgBid: 23 },
  { name: "FeralEevee#133", avgBid: 23 },
  { name: "Lolcavan#NA1", avgBid: 22 },
  { name: "08 Mitsu Eclipse#Chime", avgBid: 21 },
  { name: "Angrodis", avgBid: 20 },
  { name: "Beg#DU1", avgBid: 20 },
  { name: "solomon#meow", avgBid: 20 },
  { name: "TheMooseRules#NA1", avgBid: 20 },
  { name: "DeathMasterPwnz2#NARC", avgBid: 20 },
  { name: "Quetips#na1", avgBid: 18 },
  { name: "the grip reaper #meow", avgBid: 17 },
  { name: "Humble#btc", avgBid: 15 },
  { name: "WrathOfSath", avgBid: 15 },
  { name: "I am atomic#idk", avgBid: 15 },
  { name: "all gucci#gamer", avgBid: 10 },
  { name: "Boat chicken#na1", avgBid: 10 },
  { name: "Conguitos#01203", avgBid: 10 },
  { name: "Imperialarcher#ezpz", avgBid: 10 },
  { name: "Nickle#2537", avgBid: 10 },
  { name: "Pr1mus#NA1", avgBid: 10 },
  { name: "Promech#NA1", avgBid: 10 },
  { name: "SeeU#Xiyue", avgBid: 10 },
  { name: "SirJoey#Valor", avgBid: 10 },
  { name: "UnluckyCanadian#CDN", avgBid: 10 },
  { name: "ΣΠΑΡΤΙΑΤΗΣ #Sprtn", avgBid: 10 },
];
export const FREE_AGENCY_CAPTAINS: FreeAgencyCaptain[] = [
  {
    name: "iEnders",
    players: [
      { name: "Canny#rip", avgBid: 50 },
      { name: "Pinei nessa poha#00027", avgBid: 50 },
      { name: "JayDK#NA1", avgBid: 40 },
      { name: "Doug#LIMU", avgBid: 40 },
      { name: "Chief#1160", avgBid: 40 },
      { name: "Superbeans#222", avgBid: 30 },
      { name: "Cherrie", avgBid: 20 },
      { name: "YWGI#rain", avgBid: 15 },
      { name: "Crabadabadoo", avgBid: 30 },
      { name: "Angrodis", avgBid: 20 },
      { name: "Boat chicken#na1", avgBid: 10 },
      { name: "UnluckyCanadian#CDN", avgBid: 10 },
    ],
  },
  {
    name: "Flyinq Squirtle",
    players: [
      { name: "Canny#rip", avgBid: 50 },
      { name: "Matrix#NA101", avgBid: 40 },
      { name: "Pinei nessa poha#00027", avgBid: 30 },
      { name: "Killer Python#NA1", avgBid: 50 },
      { name: "VIP Peekaboo#VIP", avgBid: 40 },
      { name: "Aura#5950", avgBid: 40 },
      { name: "Superbeans#222", avgBid: 30 },
      { name: "i fear nobody#na1", avgBid: 20 },
      { name: "08 Mitsu Eclipse#Chime", avgBid: 15 },
      { name: "TheMooseRules#NA1", avgBid: 20 },
      { name: "Imperialarcher#ezpz", avgBid: 10 },
      { name: "Pr1mus#NA1", avgBid: 10 },
    ],
  },
  {
    name: "YRW",
    players: [
      { name: "Canny#rip", avgBid: 50 },
      { name: "Matrix#NA101", avgBid: 50 },
      { name: "Pinei nessa poha#00027", avgBid: 30 },
      { name: "Chief#1160", avgBid: 30 },
      { name: "Superbeans#222", avgBid: 40 },
      { name: "Rutledge#osu", avgBid: 40 },
      { name: "i fear nobody#na1", avgBid: 20 },
      { name: "Thunder Master#BLOOD", avgBid: 20 },
      { name: "Lolcavan#NA1", avgBid: 40 },
      { name: "08 Mitsu Eclipse#Chime", avgBid: 15 },
      { name: "DeathMasterPwnz2#NARC", avgBid: 10 },
      { name: "Conguitos#01203", avgBid: 10 },
    ],
  },
  {
    name: "Lizzo Mukkbang",
    players: [
      { name: "Canny#rip", avgBid: 50 },
      { name: "Matrix#NA101", avgBid: 30 },
      { name: "Doug#LIMU", avgBid: 50 },
      { name: "VIP Peekaboo#VIP", avgBid: 40 },
      { name: "Chief#1160", avgBid: 30 },
      { name: "Rutledge#osu", avgBid: 20 },
      { name: "Cherrie", avgBid: 20 },
      { name: "YWGI#rain", avgBid: 15 },
      { name: "FeralEevee#133", avgBid: 40 },
      { name: "Lolcavan#NA1", avgBid: 40 },
      { name: "Imperialarcher#ezpz", avgBid: 10 },
      { name: "Pr1mus#NA1", avgBid: 10 },
    ],
  },
  {
    name: "MetaShift",
    players: [
      { name: "Canny#rip", avgBid: 50 },
      { name: "Matrix#NA101", avgBid: 50 },
      { name: "LotusB5#999", avgBid: 40 },
      { name: "JayDK#NA1", avgBid: 40 },
      { name: "Doug#LIMU", avgBid: 30 },
      { name: "Thunder Master#BLOOD", avgBid: 20 },
      { name: "YWGI#rain", avgBid: 40 },
      { name: "Lolcavan#NA1", avgBid: 10 },
      { name: "08 Mitsu Eclipse#Chime", avgBid: 30 },
      { name: "Beg#DU1", avgBid: 20 },
      { name: "Humble#btc", avgBid: 15 },
      { name: "Promech#NA1", avgBid: 10 },
    ],
  },
  {
    name: "7gen",
    players: [
      { name: "Canny#rip", avgBid: 40 },
      { name: "Pinei nessa poha#00027", avgBid: 50 },
      { name: "JayDK#NA1", avgBid: 40 },
      { name: "Aura#5950", avgBid: 30 },
      { name: "Walt#0001", avgBid: 40 },
      { name: "Qball#1032", avgBid: 30 },
      { name: "MMO#NA1", avgBid: 50 },
      { name: "FeralEevee#133", avgBid: 15 },
      { name: "solomon#meow", avgBid: 20 },
      { name: "Quetips#na1", avgBid: 20 },
      { name: "Conguitos#01203", avgBid: 10 },
      { name: "ΣΠΑΡΤΙΑΤΗΣ #Sprtn", avgBid: 10 },
    ],
  },
  {
    name: "Sycoghost",
    players: [
      { name: "Matrix#NA101", avgBid: 40 },
      { name: "Pinei nessa poha#00027", avgBid: 50 },
      { name: "LotusB5#999", avgBid: 40 },
      { name: "JayDK#NA1", avgBid: 40 },
      { name: "Chief#1160", avgBid: 30 },
      { name: "Cherrie", avgBid: 20 },
      { name: "GratxAce#NA1", avgBid: 30 },
      { name: "i fear nobody#na1", avgBid: 20 },
      { name: "FeralEevee#133", avgBid: 15 },
      { name: "Lolcavan#NA1", avgBid: 10 },
      { name: "ΣΠΑΡΤΙΑΤΗΣ #Sprtn", avgBid: 10 },
    ],
  },
  {
    name: "Bleedinwolves",
    players: [
      { name: "Matrix#NA101", avgBid: 50 },
      { name: "LotusB5#999", avgBid: 50 },
      { name: "JayDK#NA1", avgBid: 30 },
      { name: "VIP Peekaboo#VIP", avgBid: 30 },
      { name: "Qball#1032", avgBid: 40 },
      { name: "Cherrie", avgBid: 40 },
      { name: "i fear nobody#na1", avgBid: 20 },
      { name: "Thunder Master#BLOOD", avgBid: 20 },
      { name: "YWGI#rain", avgBid: 15 },
      { name: "FeralEevee#133", avgBid: 40 },
      { name: "Lolcavan#NA1", avgBid: 10 },
      { name: "Conguitos#01203", avgBid: 10 },
    ],
  },
  {
    name: "Winter",
    players: [
      { name: "Matrix#NA101", avgBid: 40 },
      { name: "Pinei nessa poha#00027", avgBid: 30 },
      { name: "VIP Peekaboo#VIP", avgBid: 50 },
      { name: "Chief#1160", avgBid: 40 },
      { name: "Aura#5950", avgBid: 30 },
      { name: "Cherrie", avgBid: 20 },
      { name: "i fear nobody#na1", avgBid: 40 },
      { name: "Crabadabadoo", avgBid: 20 },
      { name: "DeathMasterPwnz2#NARC", avgBid: 50 },
      { name: "the grip reaper #meow", avgBid: 15 },
      { name: "UnluckyCanadian#CDN", avgBid: 10 },
      { name: "ΣΠΑΡΤΙΑΤΗΣ #Sprtn", avgBid: 10 },
    ],
  },
  {
    name: "Wellshowthemall",
    players: [
      { name: "Matrix#NA101", avgBid: 40 },
      { name: "LotusB5#999", avgBid: 40 },
      { name: "Chief#1160", avgBid: 50 },
      { name: "Zoodiac#すべて同じ", avgBid: 30 },
      { name: "Rutledge#osu", avgBid: 40 },
      { name: "Cherrie", avgBid: 50 },
      { name: "Thunder Master#BLOOD", avgBid: 20 },
      { name: "YWGI#rain", avgBid: 20 },
      { name: "Lolcavan#NA1", avgBid: 15 },
      { name: "08 Mitsu Eclipse#Chime", avgBid: 30 },
      { name: "all gucci#gamer", avgBid: 10 },
      { name: "SeeU#Xiyue", avgBid: 10 },
    ],
  },
  {
    name: "Spies",
    players: [
      { name: "Matrix#NA101", avgBid: 30 },
      { name: "Pinei nessa poha#00027", avgBid: 40 },
      { name: "Superbeans#222", avgBid: 30 },
      { name: "Dariss#na1", avgBid: 40 },
      { name: "Rutledge#osu", avgBid: 20 },
      { name: "MMO#NA1", avgBid: 15 },
      { name: "i fear nobody#na1", avgBid: 20 },
      { name: "Thunder Master#BLOOD", avgBid: 50 },
      { name: "YWGI#rain", avgBid: 50 },
      { name: "Lolcavan#NA1", avgBid: 40 },
      { name: "DeathMasterPwnz2#NARC", avgBid: 10 },
      { name: "Conguitos#01203", avgBid: 10 },
    ],
  },
  {
    name: "KingOfSpades",
    players: [
      { name: "Pinei nessa poha#00027", avgBid: 50 },
      { name: "JayDK#NA1", avgBid: 50 },
      { name: "Doug#LIMU", avgBid: 40 },
      { name: "Zoodiac#すべて同じ", avgBid: 40 },
      { name: "Superbeans#222", avgBid: 30 },
      { name: "Dariss#na1", avgBid: 30 },
      { name: "i fear nobody#na1", avgBid: 40 },
      { name: "FeralEevee#133", avgBid: 15 },
      { name: "the grip reaper #meow", avgBid: 20 },
      { name: "I am atomic#idk", avgBid: 20 },
      { name: "Boat chicken#na1", avgBid: 10 },
      { name: "Nickle#2537", avgBid: 10 },
    ],
  },
];

export const FREE_AGENCY_CAPTAIN_NAMES = FREE_AGENCY_CAPTAINS.map((captain) => captain.name);
