export interface FreeAgencyPlayer {
  name: string;
  avgBid: number | null;
}

export interface FreeAgencyCaptain {
  name: string;
  players: FreeAgencyPlayer[];
}

// Summary-authoritative rows from the PLAYER SUMMARY BIDS tab that are either
// absent from captain bid lists or need direct lookup without reconstruction.
export const FREE_AGENCY_PLAYER_SUMMARIES: FreeAgencyPlayer[] = [
  { name: "QBall", avgBid: 0 },
  { name: "I am ATOMIC", avgBid: 0 },
];

// Public Google Sheet snapshot imported on 2026-08-12 from the CAPTAIN BIDS and
// PLAYER SUMMARY BIDS tabs of the FPL master workbook. This remains a checked-in,
// deterministic snapshot and is not fetched at runtime.
export const FREE_AGENCY_CAPTAINS: FreeAgencyCaptain[] = [
  {
    name: "7gen",
    players: [
      { name: "Pinei Nessa Poha", avgBid: 45.6 },
      { name: "Canny", avgBid: 41.1 },
      { name: "I Fear Nobody", avgBid: 41.2 },
      { name: "Rutledge", avgBid: 45.6 },
      { name: "Quetips", avgBid: 26.2 },
      { name: "Winter", avgBid: 35 },
      { name: "Shanedata", avgBid: 20 },
      { name: "KingOfSpades", avgBid: 23 },
      { name: "Chime", avgBid: 17.5 },
      { name: "The Grim Queefer", avgBid: 13.8 },
      { name: "The Fool", avgBid: 10 },
      { name: "Solomon", avgBid: 20.8 },
    ],
  },
  {
    name: "Bleedinwolves",
    players: [
      { name: "I Fear Nobody", avgBid: 41.2 },
      { name: "Rutledge", avgBid: 45.6 },
      { name: "Conguitos0", avgBid: 35 },
      { name: "Balmer", avgBid: 24.3 },
      { name: "Cocoa", avgBid: 33 },
      { name: "Slimpimpin77", avgBid: 25 },
      { name: "Dariss", avgBid: 36.2 },
      { name: "Floragato", avgBid: 17.5 },
      { name: "AFKBoulder", avgBid: 26.7 },
      { name: "The Fool", avgBid: 10 },
      { name: "Lolcavan", avgBid: 10 },
      { name: "Juanitosol", avgBid: 5 },
    ],
  },
  {
    name: "Canadia",
    players: [
      { name: "Canny", avgBid: 41.1 },
      { name: "Dariss", avgBid: 36.2 },
      { name: "Pinei Nessa Poha", avgBid: 45.6 },
      { name: "Winter", avgBid: 35 },
      { name: "I Fear Nobody", avgBid: 41.2 },
      { name: "Angrodis", avgBid: 33.6 },
      { name: "Sunset Diner", avgBid: 24 },
      { name: "Kyujin", avgBid: 20 },
      { name: "Balmer", avgBid: 24.3 },
      { name: "The Grim Queefer", avgBid: 13.8 },
      { name: "UnluckyCanadian", avgBid: 18 },
      { name: "SaintofAegis", avgBid: 5 },
    ],
  },
  {
    name: "Flyinq Squirtle",
    players: [
      { name: "Rutledge", avgBid: 45.6 },
      { name: "Pinei Nessa Poha", avgBid: 45.6 },
      { name: "Angrodis", avgBid: 33.6 },
      { name: "I Fear Nobody", avgBid: 41.2 },
      { name: "YRW", avgBid: 38.1 },
      { name: "Winter", avgBid: 35 },
      { name: "Canny", avgBid: 41.1 },
      { name: "Quetips", avgBid: 26.2 },
      { name: "Sunset Diner", avgBid: 24 },
      { name: "Sir Joey", avgBid: 10 },
      { name: "Rexcat4", avgBid: 10 },
      { name: "TMinusBOOM", avgBid: 5 },
    ],
  },
  {
    name: "Humble",
    players: [
      { name: "Pinei Nessa Poha", avgBid: 45.6 },
      { name: "I Fear Nobody", avgBid: 41.2 },
      { name: "Rutledge", avgBid: 45.6 },
      { name: "YRW", avgBid: 38.1 },
      { name: "Aura", avgBid: 27.5 },
      { name: "Winter", avgBid: 35 },
      { name: "Angrodis", avgBid: 33.6 },
      { name: "Cocoa", avgBid: 33 },
      { name: "KingOfSpades", avgBid: 23 },
      { name: "Dawnfate", avgBid: 16 },
      { name: "The Fool", avgBid: 10 },
      { name: "Solomon", avgBid: 20.8 },
    ],
  },
  {
    name: "Imthegeoff",
    players: [
      { name: "Pinei Nessa Poha", avgBid: 45.6 },
      { name: "I Fear Nobody", avgBid: 41.2 },
      { name: "Begfourmercy", avgBid: 31.2 },
      { name: "Canny", avgBid: 41.1 },
      { name: "Winter", avgBid: 35 },
      { name: "Aura", avgBid: 27.5 },
      { name: "Angrodis", avgBid: 33.6 },
      { name: "Sunset Diner", avgBid: 24 },
      { name: "Balmer", avgBid: 24.3 },
      { name: "Dawnfate", avgBid: 16 },
      { name: "The Grim Queefer", avgBid: 13.8 },
      { name: "Blind Hookers", avgBid: 5 },
    ],
  },
  {
    name: "Lizzo Mukkbang",
    players: [
      { name: "Canny", avgBid: 41.1 },
      { name: "Rutledge", avgBid: 45.6 },
      { name: "YRW", avgBid: 38.1 },
      { name: "UnluckyCanadian", avgBid: 18 },
      { name: "Solomon", avgBid: 20.8 },
      { name: "Balmer", avgBid: 24.3 },
      { name: "Zygg", avgBid: 21.7 },
      { name: "KingOfSpades", avgBid: 23 },
      { name: "Slimpimpin77", avgBid: 25 },
      { name: "Lolcavan", avgBid: 10 },
      { name: "Dawnfate", avgBid: 16 },
      { name: "BigRed2000", avgBid: 5 },
    ],
  },
  {
    name: "Metashift",
    players: [
      { name: "Cocoa", avgBid: 33 },
      { name: "Conguitos0", avgBid: 35 },
      { name: "Angrodis", avgBid: 33.6 },
      { name: "Pinei Nessa Poha", avgBid: 45.6 },
      { name: "YWGI", avgBid: 27.5 },
      { name: "Begfourmercy", avgBid: 31.2 },
      { name: "Winter", avgBid: 35 },
      { name: "Balmer", avgBid: 24.3 },
      { name: "Aura", avgBid: 27.5 },
      { name: "Sharkbate59", avgBid: 10 },
      { name: "The Grim Queefer", avgBid: 13.8 },
      { name: "Earthen", avgBid: 5 },
    ],
  },
  {
    name: "Spies",
    players: [
      { name: "Rutledge", avgBid: 45.6 },
      { name: "Winter", avgBid: 35 },
      { name: "AFKBoulder", avgBid: 26.7 },
      { name: "Dariss", avgBid: 36.2 },
      { name: "Cocoa", avgBid: 33 },
      { name: "Canny", avgBid: 41.1 },
      { name: "YRW", avgBid: 38.1 },
      { name: "Slimpimpin77", avgBid: 25 },
      { name: "Solomon", avgBid: 20.8 },
      { name: "UnluckyCanadian", avgBid: 18 },
      { name: "The Grim Queefer", avgBid: 13.8 },
      { name: "Earthen", avgBid: 5 },
    ],
  },
  {
    name: "Sycoghost",
    players: [
      { name: "Pinei Nessa Poha", avgBid: 45.6 },
      { name: "Rutledge", avgBid: 45.6 },
      { name: "Angrodis", avgBid: 33.6 },
      { name: "Begfourmercy", avgBid: 31.2 },
      { name: "YRW", avgBid: 38.1 },
      { name: "I Fear Nobody", avgBid: 41.2 },
      { name: "Slimpimpin77", avgBid: 25 },
      { name: "Zygg", avgBid: 21.7 },
      { name: "Kyujin", avgBid: 20 },
      { name: "The Grim Queefer", avgBid: 13.8 },
      { name: "Zeldaguy0", avgBid: 10 },
      { name: "BigRed2000", avgBid: 5 },
    ],
  },
  {
    name: "Tauty2k",
    players: [
      { name: "Rutledge", avgBid: 45.6 },
      { name: "Canny", avgBid: 41.1 },
      { name: "Winter", avgBid: 35 },
      { name: "YRW", avgBid: 38.1 },
      { name: "KingOfSpades", avgBid: 23 },
      { name: "Quetips", avgBid: 26.2 },
      { name: "Slimpimpin77", avgBid: 25 },
      { name: "Kyujin", avgBid: 20 },
      { name: "Balmer", avgBid: 24.3 },
      { name: "Lolcavan", avgBid: 10 },
      { name: "ReginaldDwight", avgBid: 13.3 },
      { name: "Earthen", avgBid: 5 },
    ],
  },
  {
    name: "Zhaphh",
    players: [
      { name: "YRW", avgBid: 38.1 },
      { name: "Solomon", avgBid: 20.8 },
      { name: "The Grim Queefer", avgBid: 13.8 },
      { name: "Canny", avgBid: 41.1 },
      { name: "Dawnfate", avgBid: 16 },
      { name: "Crabadabadoo", avgBid: 20 },
      { name: "Sunset Diner", avgBid: 24 },
      { name: "ReginaldDwight", avgBid: 13.3 },
      { name: "UnluckyCanadian", avgBid: 18 },
      { name: "Zeldaguy0", avgBid: 10 },
      { name: "Lolcavan", avgBid: 10 },
      { name: "Blind Hookers", avgBid: 5 },
    ],
  },
];
