import { Fragment } from "react";
import { ROLE_LABELS_SHORT } from "@/lib/draft/types";
import type { ScoutScope, ScopedScoutData } from "@/lib/scouting/types";
import ChampionDatum from "./ChampionDatum";
import type { InhousePlayerStats } from "@/lib/scouting/inhouse";

export default function ScoutPlayerPools({ data, scope, unavailable = false, mode = "regular", onModeChange, inhousePlayers = [] }: { data: ScopedScoutData; scope: ScoutScope; unavailable?: boolean; mode?: "regular" | "inhouse"; onModeChange?: () => void; inhousePlayers?: InhousePlayerStats[] }) {
  const scopeLabel = scope === "season" ? "Current season" : scope === "recent" ? "Recent 5 series" : "All history";
  return <section aria-labelledby="player-pools-heading" className="card-brand p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="player-pools-heading" className="type-display text-2xl">{mode === "inhouse" ? "In-house champion stats" : "Player pools"}</h2><div className="flex items-center gap-3">{mode === "regular" ? <span className="label-dash">{scopeLabel}</span> : <span className="label-dash text-cyan">All available games</span>}<button type="button" role="switch" aria-checked={mode === "inhouse"} onClick={onModeChange} className="flex items-center gap-2 rounded-full border border-border-subtle bg-surface px-3 py-1.5 text-xs font-semibold uppercase tracking-wide text-muted transition hover:border-cyan/60 hover:text-white"><span className={`h-2.5 w-2.5 rounded-full ${mode === "inhouse" ? "bg-cyan shadow-[0_0_8px_rgb(53_230_255/0.8)]" : "bg-muted/50"}`} />{mode === "inhouse" ? "In-house" : "Regular season"}</button></div></div>{mode === "inhouse" ? <ul className="mt-4 grid gap-3">{inhousePlayers.map((player) => <li key={player.playerId} className="rounded border border-border-subtle/70 bg-canvas/40 p-3"><div className="flex items-baseline justify-between gap-2"><span className="font-semibold text-white">{player.playerName}</span><span className="text-xs uppercase tracking-wider text-muted">{ROLE_LABELS_SHORT[player.role]} · {player.games} games</span></div>{player.champions.length === 0 ? <p className="mt-3 text-sm text-muted">No in-house games found</p> : <div className="mt-3 flex flex-wrap gap-2">{player.champions.slice(0, 5).map((champion) => <div key={champion.champion} className="flex items-center gap-1.5"><ChampionDatum champion={champion.champion} /><span className="self-center text-xs text-muted">×{champion.games} · {champion.winrate_pct.toFixed(0)}% · {champion.avg_kda.toFixed(2)} KDA</span></div>)}</div>}</li>)}</ul> : unavailable ? <p className="mt-4 text-sm text-muted">Current roster unavailable</p> : <ul className="mt-4 grid gap-3">{data.playerPools.map((row) => <li key={row.playerName} className="rounded border border-border-subtle/70 bg-canvas/40 p-3"><div className="flex items-baseline justify-between gap-2"><span className="font-semibold text-white">{row.playerName}</span><span className="text-xs uppercase tracking-wider text-muted">{ROLE_LABELS_SHORT[row.role]}</span></div>{row.totalPicks === 0 ? <p className="mt-3 text-sm text-muted">No attributed picks yet</p> : <div className="mt-3 flex flex-wrap gap-2">{row.champions.slice(0, 5).map((champion) => <Fragment key={champion.champion}><ChampionDatum champion={champion.champion} /><span className="self-center text-xs text-muted">×{champion.count}</span></Fragment>)}</div>}<p className="mt-3 text-xs text-muted">{row.totalPicks} picks · {row.distinctChampions} champions · {row.gamesSampled} games</p></li>)}</ul>}</section>;
}
