import type { ScopedScoutData } from "@/lib/scouting/types";
import ChampionDatum from "./ChampionDatum";

function Ranked({ title, rows, tone = "neutral" }: { title: string; rows: { champion: string; count: number; rate?: number }[]; tone?: "neutral" | "ban" }) {
  return <div className="rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">{title}</h3>{rows.length ? <ul className="mt-3 space-y-2">{rows.slice(0, 5).map((row) => <li key={row.champion} className="flex items-center justify-between gap-3"><ChampionDatum champion={row.champion} tone={tone} /><span className="shrink-0 text-xs text-steel">{row.count}{row.rate !== undefined ? ` · ${row.rate}%` : ""}</span></li>)}</ul> : <p className="mt-3 text-sm text-steel">No recorded patterns yet.</p>}</div>;
}

export default function ScoutPatterns({ data }: { data: ScopedScoutData }) {
  return <section aria-labelledby="patterns-heading" className="card-brand p-5"><h2 id="patterns-heading" className="type-display text-2xl">Draft patterns</h2><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Ranked title="First picks" rows={data.firstPicks} /><Ranked title="Bans against" rows={data.bannedAgainst} tone="ban" /><Ranked title="Ban phase 1 · first 3" rows={data.banPhaseOne} tone="ban" /><Ranked title="Ban phase 2 · last 2" rows={data.banPhaseTwo} tone="ban" /></div><div className="mt-3 grid gap-3 md:grid-cols-2"><Ranked title="Opening sequences" rows={data.openings} /><Ranked title="Champion pairings" rows={data.pairings} /></div><div className="mt-3 grid gap-3 md:grid-cols-2"><div className="rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">Side samples</h3><div className="mt-3 flex flex-wrap gap-2">{data.sideFacts.map((side) => <span key={side.side} className="rounded border border-line px-2 py-1 text-xs text-steel">{side.side === "blue" ? "Blue" : "Red"}: {side.games} games{side.commonOpening ? ` · ${side.commonOpening.champion}` : ""}</span>)}</div></div><div className="rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">Adaptation notes</h3><p className="mt-3 text-sm text-steel">{data.adaptation.lossesFollowed} losses followed · {data.adaptation.changedFirstPick} changed first picks · {data.adaptation.repeatedChampions} repeated champions</p></div></div>{data.flexes.length ? <div className="mt-3 rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">Flex roles</h3><div className="mt-3 flex flex-wrap gap-2">{data.flexes.map((flex) => <span key={flex.champion} className="rounded border border-line px-2 py-1 text-xs text-steel">{flex.champion} · {flex.roles.join(" / ")}</span>)}</div></div> : null}</section>;
}
