import type { FullDraftSide, PastDraft } from "@/lib/scouting/types";
import ChampionDatum from "./ChampionDatum";

function Side({ side, value }: { side: "blue" | "red"; value: FullDraftSide }) {
  const tone = side === "blue" ? "pick-blue" : "pick-red";
  return <div className="rounded border border-line/70 bg-navy/40 p-3"><h4 className="font-semibold text-white"><span>{side === "blue" ? "Blue side" : "Red side"}</span>{value.teamName ? <span className="text-steel"> · {value.teamName}</span> : null}</h4><h5 className="mt-3 text-xs uppercase tracking-wider text-steel">Ban phase 1 · first 3</h5><div className="mt-2 flex flex-wrap gap-2">{value.banPhaseOne.map((slot, i) => <ChampionDatum key={`b1-${i}`} champion={slot.champion} tone="ban" label={`B${i + 1}`} />)}</div><h5 className="mt-3 text-xs uppercase tracking-wider text-steel">Ban phase 2 · last 2</h5><div className="mt-2 flex flex-wrap gap-2">{value.banPhaseTwo.map((slot, i) => <ChampionDatum key={`b2-${i}`} champion={slot.champion} tone="ban" label={`B${i + 4}`} />)}</div><h5 className="mt-3 text-xs uppercase tracking-wider text-steel">Picks</h5><div className="mt-2 grid grid-cols-2 gap-2">{value.picks.map((slot, i) => <ChampionDatum key={`p-${i}`} champion={slot.champion} tone={tone} label={`${side === "blue" ? "B" : "R"}${i + 1}`} testId={`${side}-pick-slot`} />)}</div></div>;
}

export default function ScoutPastDrafts({ drafts }: { drafts: PastDraft[] }) {
  return <section aria-labelledby="past-drafts-heading" className="card-brand p-5"><h2 id="past-drafts-heading" className="type-display text-2xl">Past drafts</h2>{drafts.length ? <div className="mt-4 space-y-2">{drafts.map((draft) => <details key={`${draft.fixture.id}-${draft.gameNumber}`} className="group rounded border border-line/70 bg-navy/40 p-3"><summary className="cursor-pointer list-none font-semibold text-white">Game {draft.gameNumber} · {draft.fixture.team_a ?? "—"} vs {draft.fixture.team_b ?? "—"}<span className="ml-2 text-xs text-cyan">Scouted team: {draft.side === "blue" ? "Blue side" : "Red side"}</span><span className="ml-2 text-xs text-steel">{draft.winnerTeam ? `Winner: ${draft.winnerTeam}` : "Unresolved"}</span></summary><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto_1fr]"><Side side="blue" value={draft.blue} /><div className="hidden items-center justify-center text-xs uppercase tracking-wider text-steel md:flex">vs</div><Side side="red" value={draft.red} /></div></details>)}</div> : <p className="mt-4 text-sm text-steel">No recorded drafts for this opponent yet</p>}</section>;
}
