import type { ScopedScoutData } from "@/lib/scouting/types";
import ChampionDatum from "./ChampionDatum";

function Ranked({ title, rows, tone = "neutral", composite = false }: { title: string; rows: { champion: string; count: number; rate?: number }[]; tone?: "neutral" | "ban"; composite?: boolean }) {
  const max = Math.max(...rows.map((row) => row.count), 1);
  return <div className="rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">{title}</h3>{rows.length ? <ol className="mt-3 space-y-2">{rows.slice(0, 5).map((row, index) => <li key={row.champion} className="relative overflow-hidden rounded border border-line/50 p-1.5"><span className="absolute inset-y-0 left-0 bg-cyan/10" style={{ width: `${(row.count / max) * 100}%` }} aria-hidden="true" /><div className="relative flex items-center justify-between gap-3"><span className="flex min-w-0 items-center gap-1.5"><span className="w-4 text-xs text-steel">{index + 1}</span>{composite ? <span className="flex flex-wrap gap-1">{row.champion.split(/\s(?:\/|\+)\s/).map((champion) => <ChampionDatum key={champion} champion={champion} tone={tone} />)}</span> : <ChampionDatum champion={row.champion} tone={tone} />}</span><span className="shrink-0 text-xs text-steel">{row.count}{row.rate !== undefined ? ` · ${row.rate}%` : ""}</span></div></li>)}</ol> : <p className="mt-3 text-sm text-steel">No recorded patterns yet.</p>}</div>;
}

export default function ScoutPatterns({ data }: { data: ScopedScoutData }) {
  return <section aria-labelledby="patterns-heading" className="card-brand p-5"><h2 id="patterns-heading" className="type-display text-2xl">Draft patterns</h2><div className="mt-4 grid gap-3"><Ranked title="First picks" rows={data.firstPicks} /></div><div className="mt-3 grid gap-3 md:grid-cols-2"><Ranked title="Opening sequences" rows={data.openings} composite /><Ranked title="Champion pairings" rows={data.pairings} composite /></div><div className="mt-3 grid gap-3 md:grid-cols-2"><div className="rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">Side samples</h3><div className="mt-3 flex flex-wrap gap-2">{data.sideFacts.map((side) => <span key={side.side} className={`rounded border px-2 py-1 text-xs ${side.side === "blue" ? "border-cyan/50 text-cyan" : "border-purple/60 text-purple"}`}><span>{side.side === "blue" ? "Blue" : "Red"}: {side.games} drafts</span>{side.commonOpening ? <span className="ml-1 inline-flex align-middle"><ChampionDatum champion={side.commonOpening.champion} tone={side.side === "blue" ? "pick-blue" : "pick-red"} /></span> : null}</span>)}</div></div><div className="rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">Adaptation notes</h3><p className="mt-3 text-sm text-steel">{data.adaptation.lossesFollowed} losses followed · {data.adaptation.changedFirstPick} changed first picks · {data.adaptation.repeatedChampions} repeated champions</p></div></div>{data.flexes.length ? <div className="mt-3 rounded border border-line/70 bg-navy/40 p-3"><h3 className="label-dash">Flex roles</h3><div className="mt-3 flex flex-wrap gap-2">{data.flexes.map((flex) => <span key={flex.champion} className="inline-flex items-center gap-1 rounded border border-line px-2 py-1 text-xs text-steel"><ChampionDatum champion={flex.champion} /> <span>{flex.roles.join(" / ")}</span></span>)}</div></div> : null}</section>;
}
