/**
 * Builds the history a playstyle-rated season is graded against and writes
 * it to src/lib/cards/styleYardsticks.json.
 *
 * RUN IT AT EVERY SEASON ROLLOVER, before the new season's first card drop,
 * for each league's new season, and commit the file:
 *
 *   npx tsx scripts/build-style-yardstick.ts S6 A2
 *
 * Each season is graded against its own league's completed seasons — S6
 * against S1-S5, A2 against A1 — so the season that just finished is part of
 * the next one's yardstick. A style the league's own history has seen too
 * rarely borrows the other league's games for that style alone; a league
 * with no history at all borrows everything (and says so in the file).
 *
 * What it writes, per season (src/lib/cards/styleRating.ts, StyleYardstick):
 *  - each style's stat distributions, per role and per class;
 *  - each style's farm and lane offsets (what "normal" is for a tank's CS);
 *  - the OVR curve, fitted so the new rating mints as many Master and
 *    Challenger cards a week as the old one did over the same history.
 *
 * Entries for other seasons are kept, so a season's cards keep grading
 * against the history they were printed with and a rebuild of its editions
 * reproduces them. Re-running a season replaces only that season's entry.
 * A season's ratings change if you re-run it after its cards are out, so
 * don't, unless that is the point.
 *
 * Reads raw_stats (read-only) with SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY,
 * or a JSON export of it with --from-file:
 *
 *   npx tsx scripts/build-style-yardstick.ts S6 --from-file scripts/data/raw_stats.json
 */
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { createClient } from "@supabase/supabase-js";
import { compareSeasonCodes, seasonBelongsToLeague } from "../src/lib/league/season";
import { fetchAllPages } from "../src/lib/supabase/pagination";
import { WEEKLY_STAT_COLUMNS } from "../src/lib/stats/weekly";
import { buildStyleYardstick, type HistoryRow } from "../src/lib/cards/styleYardstickBuilder";
import type { StyleYardstickFile } from "../src/lib/cards/styleYardsticks";

const OUT = "src/lib/cards/styleYardsticks.json";

/** Everything the weekly aggregation, the card engine and the style rating
 *  read from a game. */
export const HISTORY_COLUMNS = [
  ...new Set([
    ...WEEKLY_STAT_COLUMNS,
    "game_date",
    "match_id",
    "team_name",
    "team_side",
    "champion",
    "role",
    "season",
    "game_duration_min",
    "total_damage_to_champions",
    "damage_share_pct",
    "damage_taken",
    "damage_mitigated",
    "time_ccing_others_s",
    "effective_heal_and_shield",
    "turret_damage",
    "wards_killed",
    "control_wards_bought",
    "detector_wards_placed",
  ]),
].join(", ");

const ABOUT =
  "Generated by scripts/build-style-yardstick.ts — do not edit by hand. Each season is graded against the league's " +
  "completed seasons before it; re-run the script for the new seasons at every rollover and commit this file.";

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set`);
  return value;
}

async function loadRows(fromFile: string | null): Promise<HistoryRow[]> {
  const rows = fromFile
    ? (JSON.parse(readFileSync(fromFile, "utf8")) as HistoryRow[])
    : await (() => {
      const supabase = createClient(requireEnv("SUPABASE_URL"), requireEnv("SUPABASE_SERVICE_ROLE_KEY"), {
        auth: { persistSession: false },
      });
      return fetchAllPages<HistoryRow>((from, to) => supabase.from("raw_stats").select(HISTORY_COLUMNS).order("id").range(from, to));
    })();
  return uniqueGames(rows);
}

/** One row per player per match — raw_stats' own unique key. An export
 *  can repeat a match (scripts/data/raw_stats.json does), and a repeated
 *  game would count twice in every distribution and weekly cohort. */
export function uniqueGames(rows: HistoryRow[]): HistoryRow[] {
  const seen = new Set<string>();
  return rows.filter((row) => {
    const key = `${row.match_id}|${row.summoner_name}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function bySeason(rows: HistoryRow[], keep: (season: string) => boolean): Map<string, HistoryRow[]> {
  const seasons = new Map<string, HistoryRow[]>();
  for (const row of rows) {
    const season = row.season?.trim().toLocaleUpperCase();
    if (!season || !keep(season)) continue;
    const list = seasons.get(season);
    if (list) list.push(row);
    else seasons.set(season, [row]);
  }
  return seasons;
}

/** Pretty JSON with every array of numbers (or codes) on one line, so a
 *  regeneration reads as a diff of distributions rather than of lines. */
export function formatYardsticks(file: StyleYardstickFile): string {
  return `${JSON.stringify(file, null, 2).replace(/\[\n\s+([^[\]{}]*?)\n\s+\]/g, (_, inner: string) => `[${inner.split(/,\n\s+/).join(", ")}]`)}\n`;
}

/** Builds one yardstick per target season from `rows`, merged over `existing`. */
export function buildYardsticks(rows: HistoryRow[], targets: string[], existing: StyleYardstickFile | null): StyleYardstickFile {
  const seasons: StyleYardstickFile["seasons"] = { ...(existing?.seasons ?? {}) };
  const wanted = targets.map((code) => code.trim().toLocaleUpperCase());
  for (const target of wanted) {
    const league = seasonBelongsToLeague(target, "academy") ? "academy" : "premier";
    const other = league === "academy" ? "premier" : "academy";
    const own = bySeason(rows, (season) => seasonBelongsToLeague(season, league) && compareSeasonCodes(season, target) < 0);
    const borrow = bySeason(rows, (season) => seasonBelongsToLeague(season, other) && !wanted.includes(season));
    seasons[target] = buildStyleYardstick({ league, own, borrow });
  }
  const ordered = Object.fromEntries(Object.entries(seasons).sort(([a], [b]) => compareSeasonCodes(a, b)));
  return { about: ABOUT, seasons: ordered };
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const fileFlag = args.indexOf("--from-file");
  const fromFile = fileFlag === -1 ? null : args[fileFlag + 1] ?? null;
  const targets = args.filter((arg, i) => !arg.startsWith("--") && !(fileFlag !== -1 && i === fileFlag + 1));
  if (!targets.length) throw new Error("Name the season(s) to build, e.g. npx tsx scripts/build-style-yardstick.ts S6 A2");

  const rows = await loadRows(fromFile);
  const existing = (() => {
    try {
      return JSON.parse(readFileSync(OUT, "utf8")) as StyleYardstickFile;
    } catch {
      return null;
    }
  })();
  const file = buildYardsticks(rows, targets, existing);
  writeFileSync(OUT, formatYardsticks(file));

  for (const target of targets.map((t) => t.trim().toLocaleUpperCase())) {
    const y = file.seasons[target];
    console.log(
      `${target} (${y.league}): graded against ${y.history.join(", ") || "nothing"} — ${y.games} player-games; ` +
        `curve ${y.curve.base} + ${y.curve.scale} x score` +
        (y.borrowed?.length ? `; borrowed from the other league: ${y.borrowed.join(", ")}` : ""),
    );
  }
  console.log(`Wrote ${OUT}. Commit it before the season's first drop.`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
