// The style-aware card rating — how cards are rated from S6 and A2 on.
//
//   score = 30% winning + 40% fundamentals + 30% playstyle
//
// WHY. The rating this replaces judged every player in a role on one fixed
// set of stats. In mid that set was a mage's job: damage and damage share
// carried ~23% of the score and kills ~4.5%, so an assassin who won their
// games the way assassins win them read like a mage who played badly, and a
// tank's crowd control and soaking were not read at all. Measured over
// S1-S4, a top-quarter mid mage game scored at the 83rd percentile of mid
// games and a top-quarter assassin game at the 75th; tanks sat lower still.
// The design and the numbers behind it:
// docs/superpowers/specs/2026-09-25-style-aware-card-ratings-design.md
//
// WINNING is the raw win rate, exactly as before.
//
// FUNDAMENTALS are the role's checklist — laning, kill participation, vision,
// not dying, objectives for a jungler — percentiled against this window's
// role cohort, like every bar before them. Farm and laning are graded
// against the player's own STYLE's normal: a tank is not expected to farm
// like a bruiser, and a roaming assassin gives up CS a mage keeps. The
// offsets that encode "normal" come from history (see StyleYardstick).
//
// PLAYSTYLE grades each game on the job its champion does, against the
// league's history of that same style in that same role: an assassin's
// kills against other assassins' kills, a tank's crowd control against other
// tanks'. Different jobs, one yardstick — "how far above a typical game of
// your style was this?" — so an elite assassin game and an elite mage game
// land in the same place. A week averages its games, each graded by its own
// champion, so a player who went Zed then Orianna was an assassin in one and
// a mage in the other.
//
// Pure functions: the yardstick arrives as data (styleYardsticks.ts loads
// the generated file for the data layer), so this module stays free of it.

import type { PlayerAggRow } from "@/lib/stats/types";
import type { CardGameMeta, CardGameRow, CardPercentile } from "./build";
import { type GameTotals, STYLE_MEASURE_LABELS, type StyleMeasureKey, pctOf } from "./measures";
import { type ChampionClass, type Playstyle, championClass, playstyleOf, windowPlaystyleLabel } from "./playstyle";

/** A per-game stat a style can be graded on. */
export type StyleStat =
  | "kills"
  | "solo"
  | "dmg"
  | "share"
  | "cc"
  | "twr"
  | "mitPct"
  | "mitigated"
  | "takenShare"
  | "heal"
  | "assists";

/**
 * What each style is FOR: stat -> weight within the style's grade.
 *
 * Every stat here was checked against winning INSIDE its own style over
 * S1-S4, because a stat that piles up in losses pays players for losing.
 * Two candidates failed that test and are deliberately absent:
 *  - bounty gold (r = -0.23 to -0.37 with winning): shutdowns are collected
 *    off enemies who are ahead, so it mostly measures being behind;
 *  - raw damage TAKEN per minute for tanks (r about -0.22): an enemy team
 *    that is ahead hits harder. A tank's soaking is measured instead as its
 *    share of its own team's damage taken — how much of the fight it
 *    absorbed for its carries — which is neutral to winning.
 *
 * Tanks and engage supports use the league's own definition of the job:
 * crowd control, soaking for the team, and damage mitigated.
 *
 * Keyed by Playstyle, which covers every ChampionClass name too, so a rare
 * style falling back to its class finds a lens either way.
 */
export const STYLE_LENSES: Record<Playstyle, [StyleStat, number][]> = {
  assassin: [["kills", 0.4], ["solo", 0.3], ["dmg", 0.3]],
  carry: [["kills", 0.4], ["dmg", 0.35], ["solo", 0.25]],
  mage: [["dmg", 0.5], ["share", 0.25], ["cc", 0.25]],
  marksman: [["dmg", 0.4], ["twr", 0.35], ["share", 0.25]],
  ranged: [["dmg", 0.45], ["twr", 0.3], ["share", 0.25]],
  bruiser: [["dmg", 0.35], ["twr", 0.25], ["mitPct", 0.2], ["solo", 0.2]],
  skirmisher: [["solo", 0.35], ["twr", 0.35], ["dmg", 0.3]],
  fighter: [["dmg", 0.4], ["solo", 0.3], ["kills", 0.3]],
  tank: [["cc", 0.4], ["takenShare", 0.3], ["mitigated", 0.3]],
  engage: [["cc", 0.4], ["takenShare", 0.3], ["mitigated", 0.3]],
  enchanter: [["heal", 0.5], ["assists", 0.5]],
  other: [["dmg", 0.5], ["assists", 0.5]],
};

/** A style needs this many historical games in its role before it is graded
 *  against its own history; fewer, and it borrows its class's games from
 *  every role (a Cho'Gath bot is judged as a tank). */
export const MIN_STYLE_GAMES = 20;

/** Farm and lane inputs, which are graded against the player's own style. */
export type FarmInput = "cs" | "csd" | "gd" | "xpd";

/**
 * The history a style-rated season is graded against. Generated by
 * scripts/build-style-yardstick.ts from the league's completed seasons and
 * frozen per season, so rebuilding a season's editions reproduces them.
 */
export interface StyleYardstick {
  league: "premier" | "academy";
  /** The seasons whose games built it, oldest first. */
  history: string[];
  /** Distributions filled from ANOTHER league's history because this
   *  league's own was too thin: their keys, or ["all"] when the league had
   *  no history of its own at all (Academy before A1 finished). */
  borrowed?: string[];
  /** Player-games behind it. */
  games: number;
  /** OVR = base + scale x score, calibrated over the same history so this
   *  formula mints as many Master-and-above cards a week as the old one. */
  curve: { base: number; scale: number };
  /**
   * "ROLE|style" and "*|class" -> the games behind it and each lens stat's
   * quantiles at every 5th percentile (21 values, ascending).
   */
  distributions: Record<string, { games: number; stats: Partial<Record<StyleStat, number[]>> }>;
  /** "ROLE|style" -> how far that style's typical game sits from the role's,
   *  already shrunk toward zero for rarely seen styles. */
  offsets: Record<string, Partial<Record<FarmInput, number>>>;
}

/** The measures a style-rated card's bars can carry, besides the style bar. */
export type FundamentalKey = Exclude<StyleMeasureKey, "style">;

/**
 * Four fundamentals per role, and the style bar in front of them: five bars,
 * the same five slots every card has always had (the card face has no room
 * for a sixth). The card is still scored on exactly what it shows.
 *
 * Laning is CS per minute plus CS, gold and XP difference at 10 against the
 * player in the same role on the other team. A jungler's version of the same
 * thing is labelled Farming; a support's laning leaves CS out.
 */
export const STYLE_ROLE_BARS: Record<string, FundamentalKey[]> = {
  TOP: ["laning", "survival", "teamplay", "vision"],
  JUNGLE: ["objectives", "farming", "teamplay", "vision"],
  MIDDLE: ["laning", "survival", "teamplay", "vision"],
  BOTTOM: ["laning", "survival", "teamplay", "vision"],
  UTILITY: ["vision", "teamplay", "survival", "laning"],
};

const DEFAULT_STYLE_BARS: FundamentalKey[] = ["laning", "survival", "teamplay", "vision"];

/** Each fundamental's share of the score. They sum to FUNDAMENTALS_WEIGHT
 *  per role; the rest is winning and playstyle. Judgement, like the weights
 *  they replace — tune here. */
export const FUNDAMENTAL_WEIGHTS: Record<string, Partial<Record<FundamentalKey, number>>> = {
  TOP: { laning: 16, survival: 10, teamplay: 7, vision: 7 },
  JUNGLE: { objectives: 12, farming: 10, teamplay: 10, vision: 8 },
  MIDDLE: { laning: 14, survival: 10, teamplay: 9, vision: 7 },
  BOTTOM: { laning: 16, survival: 10, teamplay: 7, vision: 7 },
  UTILITY: { vision: 14, teamplay: 10, survival: 9, laning: 7 },
};

const DEFAULT_FUNDAMENTAL_WEIGHTS: Partial<Record<FundamentalKey, number>> = FUNDAMENTAL_WEIGHTS.MIDDLE;

export const WIN_WEIGHT = 30;
export const FUNDAMENTALS_WEIGHT = 40;
export const STYLE_WEIGHT = 30;

export function styleBarsForRole(roleMode: string | null | undefined): FundamentalKey[] {
  return (roleMode && STYLE_ROLE_BARS[roleMode]) || DEFAULT_STYLE_BARS;
}

export function fundamentalWeightsForRole(roleMode: string | null | undefined): Partial<Record<FundamentalKey, number>> {
  return (roleMode && FUNDAMENTAL_WEIGHTS[roleMode]) || DEFAULT_FUNDAMENTAL_WEIGHTS;
}

const num = (value: number | null | undefined): number => (typeof value === "number" && Number.isFinite(value) ? value : 0);

function mean(values: number[]): number {
  return values.reduce((s, v) => s + v, 0) / (values.length || 1);
}

/** The teams in one window, for the stats that need a game's other rows:
 *  a team's total damage taken, and the lane opponent. */
export interface GameIndex {
  /** "match|team" -> the team's total damage taken. */
  teamTaken: Map<string, number>;
  /** "match|ROLE" -> every row played in that role in that match. */
  byLane: Map<string, CardGameRow[]>;
}

const teamKey = (game: CardGameRow): string => `${game.match_id}|${(game.team_name ?? "").trim().toLowerCase()}`;
const laneKey = (matchId: string, role: string): string => `${matchId}|${role.trim().toUpperCase()}`;

export function indexGames(games: Iterable<CardGameRow>): GameIndex {
  const teamTaken = new Map<string, number>();
  const byLane = new Map<string, CardGameRow[]>();
  for (const game of games) {
    if (game.team_name) teamTaken.set(teamKey(game), (teamTaken.get(teamKey(game)) ?? 0) + num(game.damage_taken));
    if (game.role) {
      const key = laneKey(game.match_id, game.role);
      const lane = byLane.get(key);
      if (lane) lane.push(game);
      else byLane.set(key, [game]);
    }
  }
  return { teamTaken, byLane };
}

/**
 * One stat of one game, or null when the game cannot say. Rates are per
 * minute, so a long game gives no free credit; a game with no recorded
 * duration has no rates at all rather than per-game totals graded against
 * per-minute history, which would put every one of them at the top.
 */
export function styleStat(stat: StyleStat, game: CardGameRow, minutes: number, index: GameIndex): number | null {
  const rate = (value: number | null | undefined): number | null => (minutes > 0 ? num(value) / minutes : null);
  switch (stat) {
    case "kills":
      return rate(game.kills);
    case "solo":
      return rate(game.solo_kills);
    case "dmg":
      return rate(game.total_damage_to_champions);
    case "share":
      return typeof game.damage_share_pct === "number" ? game.damage_share_pct : null;
    case "cc":
      return rate(game.time_ccing_others_s);
    case "twr":
      return rate(game.turret_damage);
    case "mitPct": {
      const incoming = num(game.damage_taken) + num(game.damage_mitigated);
      return incoming > 0 ? num(game.damage_mitigated) / incoming : null;
    }
    case "mitigated":
      return rate(game.damage_mitigated);
    case "takenShare": {
      const team = game.team_name ? index.teamTaken.get(teamKey(game)) ?? 0 : 0;
      return team > 0 ? num(game.damage_taken) / team : null;
    }
    case "heal":
      return rate(game.effective_heal_and_shield);
    case "assists":
      return rate(game.assists);
  }
}

/**
 * Where `value` falls in a distribution given as quantiles at every 5th
 * percentile, 0-100. Linear between quantiles; a value sitting on a run of
 * equal quantiles (the many zero-solo-kill games, say) gets the middle of
 * the run, the same midrank the cohort percentiles use for ties.
 */
export function gradeAgainst(quantiles: number[], value: number): number {
  const last = quantiles.length - 1;
  if (last < 1) return 50;
  const step = 100 / last;
  if (value < quantiles[0]) return 0;
  if (value > quantiles[last]) return 100;
  let first = -1;
  let final = -1;
  for (let i = 0; i <= last; i += 1) {
    if (quantiles[i] === value) {
      if (first === -1) first = i;
      final = i;
    }
  }
  if (first !== -1) return ((first + final) / 2) * step;
  for (let i = 0; i < last; i += 1) {
    if (quantiles[i] < value && value < quantiles[i + 1]) {
      return (i + (value - quantiles[i]) / (quantiles[i + 1] - quantiles[i])) * step;
    }
  }
  return 50;
}

/** The distribution and lens a game is graded with: its own style in its
 *  own role when history has enough of those, else its class everywhere. */
function yardstickFor(
  yardstick: StyleYardstick,
  role: string,
  style: Playstyle,
  cls: ChampionClass,
): { lens: [StyleStat, number][]; stats: Partial<Record<StyleStat, number[]>> } | null {
  const own = yardstick.distributions[`${role}|${style}`];
  if (own && own.games >= MIN_STYLE_GAMES) return { lens: STYLE_LENSES[style], stats: own.stats };
  const byClass = yardstick.distributions[`*|${cls}`];
  if (byClass && byClass.games >= MIN_STYLE_GAMES) return { lens: STYLE_LENSES[cls], stats: byClass.stats };
  return null;
}

/** A game's playstyle grade (0-100) against history, or null when the
 *  champion is unknown or history has nothing to grade it against. */
export function gradeGame(
  game: CardGameRow,
  roleFallback: string,
  minutes: number,
  index: GameIndex,
  yardstick: StyleYardstick,
): { style: Playstyle | null; grade: number | null } {
  const role = (game.role ?? roleFallback).trim().toUpperCase();
  const style = playstyleOf(role, game.champion);
  const cls = championClass(game.champion);
  if (!style || !cls) return { style: null, grade: null };
  const target = yardstickFor(yardstick, role, style, cls);
  if (!target) return { style, grade: null };
  let total = 0;
  let used = 0;
  for (const [stat, weight] of target.lens) {
    const quantiles = target.stats[stat];
    const value = styleStat(stat, game, minutes, index);
    if (!quantiles || value === null) continue;
    total += gradeAgainst(quantiles, value) * weight;
    used += weight;
  }
  return { style, grade: used > 0 ? total / used : null };
}

/** The farm and lane numbers one game contributes, before its style's
 *  offset is taken off. Lane diffs are null with no opponent to diff.
 *  Exported so the yardstick generator measures offsets the same way. */
export function farmInputs(game: CardGameRow, role: string, index: GameIndex): { cs: number; lane: Record<Exclude<FarmInput, "cs">, number> | null } {
  const opponent = (index.byLane.get(laneKey(game.match_id, role)) ?? []).find(
    (other) => other !== game && (other.team_name ?? "").trim().toLowerCase() !== (game.team_name ?? "").trim().toLowerCase(),
  );
  const measured = (row: CardGameRow) => row.cs_at_10 != null && row.gold_at_10 != null && row.xp_at_10 != null;
  const lane = opponent && measured(game) && measured(opponent)
    ? {
      csd: num(game.cs_at_10) - num(opponent.cs_at_10),
      gd: num(game.gold_at_10) - num(opponent.gold_at_10),
      xpd: num(game.xp_at_10) - num(opponent.xp_at_10),
    }
    : null;
  return { cs: num(game.cs), lane };
}

/** One player's window, reduced to what the style rating compares. */
interface WindowFigures {
  /** Style-adjusted CS per minute, or null with no timed games. */
  cs: number | null;
  /** Style-adjusted lane diffs at 10, or null with no measurable lane. */
  csd: number | null;
  gd: number | null;
  xpd: number | null;
  /** Mean playstyle grade over graded games; null when none could be graded. */
  style: number | null;
  label: string;
}

function windowFigures(
  row: PlayerAggRow,
  games: CardGameRow[],
  gameLog: Map<string, CardGameMeta>,
  index: GameIndex,
  yardstick: StyleYardstick,
): WindowFigures {
  let cs = 0;
  let csOffset = 0;
  let minutes = 0;
  const lanes: Record<Exclude<FarmInput, "cs">, number>[] = [];
  const grades: number[] = [];
  const styles: (Playstyle | null)[] = [];
  for (const game of games) {
    const role = (game.role ?? row.role_mode).trim().toUpperCase();
    const length = gameLog.get(game.match_id)?.durationMin || num(game.game_duration_min);
    const { style, grade } = gradeGame(game, row.role_mode, length, index, yardstick);
    styles.push(style);
    if (grade !== null) grades.push(grade);
    const offset = (style && yardstick.offsets[`${role}|${style}`]) || {};
    const inputs = farmInputs(game, role, index);
    if (length > 0) {
      cs += inputs.cs;
      csOffset += num(offset.cs) * length;
      minutes += length;
    }
    if (inputs.lane) {
      lanes.push({
        csd: inputs.lane.csd - num(offset.csd),
        gd: inputs.lane.gd - num(offset.gd),
        xpd: inputs.lane.xpd - num(offset.xpd),
      });
    }
  }
  return {
    cs: minutes > 0 ? (cs - csOffset) / minutes : null,
    csd: lanes.length ? mean(lanes.map((l) => l.csd)) : null,
    gd: lanes.length ? mean(lanes.map((l) => l.gd)) : null,
    xpd: lanes.length ? mean(lanes.map((l) => l.xpd)) : null,
    style: grades.length ? mean(grades) : null,
    label: windowPlaystyleLabel(styles),
  };
}

/** Percentile of a nullable figure among the peers who have one; a player
 *  without one sits at the middle rather than at the bottom. */
function pctOfPresent(values: (number | null)[], value: number | null): number {
  if (value === null) return 50;
  return pctOf(values.filter((v): v is number => v !== null), value);
}

export interface StyleRating {
  score: number;
  overall: number;
  /** Raw 0-100 bar values; the engine squeezes them onto the card's scale. */
  bars: { key: StyleMeasureKey; label: string; value: number }[];
}

export interface RateByStyleInput {
  cohort: PlayerAggRow[];
  gamesOf: (row: PlayerAggRow) => CardGameRow[];
  /** Every game row in the window — opponents and teammates included. */
  allGames: Iterable<CardGameRow>;
  gameLog: Map<string, CardGameMeta>;
  yardstick: StyleYardstick;
  percentile: CardPercentile;
  totalsOf: (row: PlayerAggRow) => GameTotals;
}

/** Same-role cohort with the >=4-member fallback every percentile uses. */
function peersOf<T>(cohort: PlayerAggRow[], row: PlayerAggRow, pick: (r: PlayerAggRow) => T): T[] {
  const same = cohort.filter((r) => r.role_mode === row.role_mode);
  return (same.length >= 4 ? same : cohort).map(pick);
}

/** Every cohort member's style rating, keyed by their agg row. */
export function rateByStyle(input: RateByStyleInput): Map<PlayerAggRow, StyleRating> {
  const { cohort, gamesOf, gameLog, yardstick, percentile, totalsOf } = input;
  const index = indexGames(input.allGames);
  const figures = new Map<PlayerAggRow, WindowFigures>();
  for (const row of cohort) figures.set(row, windowFigures(row, gamesOf(row), gameLog, index, yardstick));

  const ratings = new Map<PlayerAggRow, StyleRating>();
  for (const row of cohort) {
    const mine = figures.get(row)!;
    const peer = (pick: (f: WindowFigures) => number | null) => peersOf(cohort, row, (r) => pick(figures.get(r)!));
    const farmLane = [
      pctOfPresent(peer((f) => f.cs), mine.cs),
      pctOfPresent(peer((f) => f.csd), mine.csd),
      pctOfPresent(peer((f) => f.gd), mine.gd),
      pctOfPresent(peer((f) => f.xpd), mine.xpd),
    ];
    const totals = totalsOf(row);
    const values: Record<FundamentalKey, number> = {
      // A support's CS is not a fundamental; their lane is gold and XP.
      laning: row.role_mode === "UTILITY" ? mean(farmLane.slice(2)) : mean(farmLane),
      farming: mean(farmLane),
      teamplay: percentile(row, "avg_kp_pct"),
      survival: percentile(row, "deathsPerMinute", true),
      vision: mean([
        percentile(row, "avg_vision_per_min"),
        pctOf(peersOf(cohort, row, (r) => totalsOf(r).visionWork), totals.visionWork),
      ]),
      objectives: pctOf(peersOf(cohort, row, (r) => totalsOf(r).objectives), totals.objectives),
    };
    // With no gradeable game the style term sits at the middle: no history
    // to compare against is not evidence of a bad week.
    const style = mine.style ?? 50;
    const weights = fundamentalWeightsForRole(row.role_mode);
    let fundamentals = 0;
    let used = 0;
    for (const [key, weight] of Object.entries(weights) as [FundamentalKey, number][]) {
      fundamentals += values[key] * weight;
      used += weight;
    }
    const fundamentalsScore = used > 0 ? fundamentals / used : 50;
    const score = (WIN_WEIGHT * row.winrate_pct + FUNDAMENTALS_WEIGHT * fundamentalsScore + STYLE_WEIGHT * style) / (WIN_WEIGHT + FUNDAMENTALS_WEIGHT + STYLE_WEIGHT);
    const overall = Math.max(1, Math.min(99, Math.round(yardstick.curve.base + score * yardstick.curve.scale)));
    ratings.set(row, {
      score,
      overall,
      bars: [
        { key: "style", label: mine.label, value: style },
        ...styleBarsForRole(row.role_mode).map((key) => ({ key, label: STYLE_MEASURE_LABELS[key], value: values[key] })),
      ],
    });
  }
  return ratings;
}
