create table if not exists public.raw_stats (
  id bigint generated always as identity primary key,
  game_date timestamp,
  match_id text,
  game_duration_min double precision,
  team_side text,
  team_name text,
  summoner_name text,
  tag text,
  champion text,
  role text,
  champion_level bigint,
  kills bigint,
  deaths bigint,
  assists bigint,
  kda double precision,
  solo_kills bigint,
  kill_participation_pct double precision,
  double_kills bigint,
  triple_kills bigint,
  quadra_kills bigint,
  penta_kills bigint,
  largest_multi_kill bigint,
  largest_killing_spree bigint,
  first_blood_kill boolean,
  first_blood_assist boolean,
  total_damage_to_champions bigint,
  damage_per_min bigint,
  damage_share_pct double precision,
  physical_damage bigint,
  magic_damage bigint,
  true_damage bigint,
  largest_critical_strike bigint,
  damage_per_gold double precision,
  damage_taken bigint,
  damage_taken_per_min bigint,
  damage_mitigated bigint,
  total_healing bigint,
  healing_on_teammates bigint,
  shielding_on_teammates bigint,
  time_ccing_others_s bigint,
  total_cc_dealt_s bigint,
  gold_earned bigint,
  gold_per_min bigint,
  gold_share_pct double precision,
  gold_spent bigint,
  consumables_purchased bigint,
  items_purchased bigint,
  cs bigint,
  cs_per_min double precision,
  lane_minions_killed bigint,
  neutral_minions_killed bigint,
  cs_at_5 bigint,
  cs_at_10 bigint,
  cs_at_15 bigint,
  cs_at_20 bigint,
  gold_at_5 bigint,
  gold_at_10 bigint,
  gold_at_15 bigint,
  gold_at_20 bigint,
  xp_at_5 bigint,
  xp_at_10 bigint,
  xp_at_15 bigint,
  xp_at_20 bigint,
  turret_plates_destroyed bigint,
  level_6_timing_min double precision,
  vision_score bigint,
  vision_score_per_min double precision,
  wards_placed bigint,
  wards_killed bigint,
  control_wards_bought bigint,
  detector_wards_placed bigint,
  stealth_wards_placed bigint,
  turret_kills bigint,
  turret_damage bigint,
  objective_damage bigint,
  inhibitor_kills bigint,
  nexus_kills bigint,
  objectives_stolen bigint,
  objectives_stolen_assists bigint,
  baron_kills bigint,
  dragon_kills bigint,
  spell1_casts_q bigint,
  spell2_casts_w bigint,
  spell3_casts_e bigint,
  spell4_casts_r bigint,
  summoner1_casts bigint,
  summoner2_casts bigint,
  longest_time_alive_s bigint,
  total_time_dead_s bigint,
  lane_minions_first_10_min bigint,
  jungle_cs_before_10_min double precision,
  max_cs_advantage_on_lane_opponent double precision,
  max_level_lead_on_lane_opponent bigint,
  skillshots_hit bigint,
  skillshots_dodged bigint,
  damage_per_minute_challenges double precision,
  team_damage_pct double precision,
  kda_challenges double precision,
  kill_participation_challenges double precision,
  effective_heal_and_shield double precision,
  bounty_gold double precision,
  vision_score_advantage_over_lane_opponent double precision,
  control_wards_placed_challenges bigint,
  wards_guarded bigint,
  first_turret_killed boolean,
  first_turret_killed_assist boolean,
  turret_plates_taken_challenges bigint,
  solo_turrets_late_game bigint,
  turret_takedowns bigint,
  game_ended_in_surrender boolean,
  game_ended_in_early_surrender boolean,
  all_in_pings bigint,
  assist_me_pings bigint,
  danger_pings bigint,
  enemy_missing_pings bigint,
  enemy_vision_pings bigint,
  on_my_way_pings bigint,
  push_pings bigint,
  need_vision_pings bigint,
  team_dragons bigint,
  team_first_dragon boolean,
  team_barons bigint,
  team_first_baron boolean,
  team_heralds bigint,
  team_first_herald boolean,
  team_grubs bigint,
  team_first_grubs boolean,
  team_towers bigint,
  team_first_tower boolean,
  team_first_blood boolean,
  win boolean,
  season_phase text,
  season text,
  ban_1 text,
  ban_2 text,
  ban_3 text,
  ban_4 text,
  ban_5 text
);

create index if not exists raw_stats_match_id_idx on public.raw_stats (match_id);
create index if not exists raw_stats_summoner_name_idx on public.raw_stats (summoner_name);

create unique index raw_stats_match_summoner_key on public.raw_stats (match_id, summoner_name);

alter table public.raw_stats enable row level security;

create policy raw_stats_public_read on public.raw_stats for select using (true);

grant select on public.raw_stats to anon, authenticated;
revoke insert, update, delete on public.raw_stats from anon, authenticated;

-- service_role bypasses RLS and needs full access for the data loader
-- (this table postdates 20260807000007_grants.sql's blanket service_role grant).
grant all on public.raw_stats to service_role;
grant usage, select on sequence public.raw_stats_id_seq to service_role;
