-- Weekly homepage write-up, generated by a Tuesday job and rendered on the
-- front page.
--
-- One row per generated brief rather than one mutable row, so an admin can
-- unpublish a bad week and the previous one takes over instead of the page
-- going blank. The generator computes every number itself and asks the model
-- only for prose, so nothing here is a source of truth for results.

create table public.homepage_briefs (
  id            uuid primary key default gen_random_uuid(),
  season        text not null,
  -- The completed week this brief covers. Null for a preseason or catch-up run.
  week          int,
  recap         text,
  preview       text,
  players_note  text,
  teams_note    text,
  league_notes  text,
  model         text,
  published     boolean not null default false,
  generated_at  timestamptz not null default now(),
  edited_by     uuid references public.profiles(id),
  edited_at     timestamptz
);

create index on public.homepage_briefs (season, published, generated_at desc);

alter table public.homepage_briefs enable row level security;

create policy homepage_briefs_public_read on public.homepage_briefs
  for select using (true);
-- Admins edit and unpublish from the admin panel; the generator writes with
-- the service role, which bypasses RLS.
create policy homepage_briefs_admin_write on public.homepage_briefs
  for all using (public.is_admin()) with check (public.is_admin());

grant select on public.homepage_briefs to anon, authenticated;
grant insert, update, delete on public.homepage_briefs to authenticated;
grant all on public.homepage_briefs to service_role;
